### ISSUE TITLE
Rozłożenie priorytetów AI

### ISSUE THREAD

**Issue by Michal-Roman0** [Michal-Roman0/ProjektEwolucja#10]
Jedzenie, ucieczka i t d

**Comment by xAdiro** [comment]
Starałem się to jakoś rozbić i mam:
# Dla roślinożerców
kwestia rozpoznania zagrożenia i jedzenia jest troszkę bardziej klarowna więc zacząłem od nich.
Roślinożercy mogą robi 3 rzeczy:
- uciekać
- jeść
- kopulować
W #9 bardziej opiszę kwestię co dokładnie te rzeczy/akcje znaczą, ale tutaj na razie jest kwestia czym w danym momencie ma się roślinożerca zająć.

## Wyrażenie priorytetów
Każdy priorytet ma jakąś wartość liczbową i organizm zajmuje się aktualnie tym którego wartość jest największa. Na początek każdy priorytet przyjąłem jako funkcję liniową. Jak się okaże że to kiepskie podejście to można kombinować z czymś potęgowym albo wykładniczym.

### Ucieczka
**U(z) = a<sub>0</sub> + a<sub>1</sub>z**
U - priorytet ucieczki
z - odległość od najbliższego drapieżnika w zasięgu wzroku
a<sub>n</sub> jakieś współczynniki które możemy na sztywno określić albo mogą być częścią ewolucji umysłu

Kwestia co zrobić gdy nie widać drapieżników. Możliwe rozwiązanie to branie `1/z` i wtedy z = ∞ i ten składnik się zeruje, ale zmienna nie jest już liniowa.

### Jedzenie
**J(g, p) = a<sub>0</sub> + a<sub>1</sub>g + a<sub>2</sub>p**
J - priorytet jedzenia
g - głód
p - odległość od najbliższego jedzenia
a<sub>n</sub> - jakieś współczynniki które możemy na sztywno określić albo mogą być częścią ewolucji umysłu

Ten sam problem co w ucieczce ze zmienną p. Generalnie z p można dużo kombinować bo może to być odległość od najbliższego jedzenia, średnia odległość od jedzenia w zasięgu wzroku, połączenie tych wartości albo jeszcze coś innego.

Głód może być wtedy `głód = 1/aktualna energia` (byłaby wtedy nieliniowa właściwość) albo po prostu `głód = -aktualna energia`

### Rozmnażanie
**R(p, o) = a<sub>0</sub> + a<sub>1</sub>p + a<sub>2</sub>o**
R - priorytet rozmnażania
p - popęd
o - odległość od najbliższego osobnika zdatnego do kopulacji

Popęd jest jakąś inną funkcją np `popęd = czas od ostatniej kopulacji` ale jest pole do manewru
Odległość od najbliższego osobnika to ten sam problem co w poprzednich dwóch priorytetach.

**Comment by Browarnik123** [comment]
Roślinożerca zarówno jak każdy inny osobnik jako maszyna stanów. Z danego stanu można przejść tylko do określonych możliwych.

Z każdego stanu można przejść do stanu "fleeing", odpowiada za to odpowiedni colider.

1.Jak osobnik jest w stanie "Idle" to analizuje swoje swoje statystyki by wyliczyć akcję z największym priorytetem.
 
2.Powiedzmy, że jest najedzony i nie ma cooldownu na kopulację to przechodzi do akcji "looking for mate".

3.Gdy w tym stanie zauważy potencjalnego partnera to przejdzie w stan "going to mate".

Natomiast jeżeli w stanie "looking for mate" wartość energii spadnie poniżej wymaganej to nastąpi powrót do stanu Idle.

4.Gdy uda mu się spotkać z partnerem to przedzie w stan "copulation".

Natomiast jeżeli w stanie "going to mate" wartość energii spadnie poniżej wymaganej to nastąpi powrót do stanu Idle.

5.Nie ważne czy kopulacja skończyła się sukcesem czy porażką, to naliczany jest copulation_cooldown(dopóki jest większy od 0 to osobnik nie może przejść w stan "looking for mate") i osobnik przechodzi do stanu "Idle".

![image](https://user-images.githubusercontent.com/43809665/227802824-240cf61f-57c5-43b1-9172-bee2ccea89a9.png)

**Comment by Browarnik123** [comment]
Wyliczanie prawdopodobieństwa sukcesu kopulacji

![image](https://user-images.githubusercontent.com/43809665/227803151-bd4880ed-69e8-4abb-bbaa-1fba08c00736.png)

**Comment by xAdiro** [comment]
Wandering Look_for_mate
Wandering Look_for_food
Wandering Flee

Flee Wandering
Look_for_mate Wandering
Look_for_mate Flee
Look_for_mate Copulating

Look_for_food Wandering
Look_for_food Flee
Look_for_food Eating

Eating Wandering
Eating Flee

Copulating Wandering
Copulating Flee

![graph](https://user-images.githubusercontent.com/51029232/229555973-00b456b2-ceea-41e2-b26e-bde7cd341960.png)

https://csacademy.com/app/graph_editor/

**Comment by xAdiro** [comment]
Finalnie stany będą wyglądać tak https://github.com/Michal-Roman0/ProjektEwolucja/issues/22#issuecomment-1494636792 
![maszyna stanowa.png](https://user-images.githubusercontent.com/51029232/229571836-e8ed5ced-ddbc-405e-8d0b-71c740afa40e.png)
Pozbywamy się więc priorytetu ucieczki i zostają priorytety rozmnażania i jedzenia.
Moje uwagi i sugestie:
- Myślę że sytuacja gdy organizm jest głodny nie powinna uniemożliwiać kopulacji jeśli ma innego osobnika pod nosem i wystarczająco energii na to
- Analogicznie jeśli jest całkiem najedzony, ale nie do końca i ma pod nosem jedzenie to czemu by się nie zatrzymać i zjeść

Mając to na uwadze trzeba ustawić warunki graniczne:
- Priorytet jedzenia powinien być duży jeśli organizm ma za mało energii na kopulacje
- Priorytet jedzenia powinien być mały jeśli organizm jest w pełni najedzony

Można też kombinować ze zbiorem wartości priorytetów (wcześniej zakładałem ℝ). Ale w sumie możliwości są:
- ℝ - najmniej kombinowania ze wzorami, ale można doprowadzić do głupot (np. próba rozmnażania się bez wystarczającej energii)
- <0:+∞> - trochę mniej swobody ale można wyznaczać akcje niemożliwe
- <0;1> - najbardziej elegancki, można wyznaczać akcje niemożliwe i wymuszone, ale trzeba gimnastyki żeby się w nim zmieścić

Jak pisałem mamy dwa warunki skrajne dla jedzenia, nie ma takiej konieczności dla rozmnażania więc jeśli chodzi o charakter funkcji to:
- priorytet jedzenia przyjmuje wartości <0;1>
- priorytet rozmnażania przyjmuje wartości (0;1)

Wszystko można wtedy sprowadzić do wielowymiarowych sigmoidów (jeśli tak to coś można nazwać), a no i to nie musi być e jako podstawa potęgowania
![image](https://user-images.githubusercontent.com/51029232/229662990-aa4b372e-6aba-4ec5-b88e-01184912cca6.png)

Nie wpadłem jeszcze jak zapisać wtedy wzór na priorytet jedzenia (w sensie te gwarantowane 0 i 1 na skrajnych warunkach), ale wiem jak powinno coś takiego wyglądać.
Z perspektywy głodu:
![image](https://user-images.githubusercontent.com/51029232/229664739-e8401e69-45c3-44ea-9e5d-7482d2210a27.png)
Z perspektywy najbliższego jedzenia
![image](https://user-images.githubusercontent.com/51029232/229664953-c318271e-c8d0-4779-835b-cdaa9c94e8b4.png)
Czyli idąc po osi głodu ten sigmoid będzie zbliżany do 0 albo 1 i na skrajach będą tylko te wartości. Wyglądałoby to mniej więcej tak:
![image](https://user-images.githubusercontent.com/51029232/229670501-70c381b5-145f-4e0e-8fbc-e4bb4d9eafd5.png)

### Wnioski
Ogólnie patrząc na te podejście matematyczne z priorytetami zaczyna to wyglądać na tyle skomplikowanie, że chyba na razie zostałbym przy podejściu algorytmicznym tzn. jeśli się naje to idzie szukać partnera. Jedyną wadą tego podejścia jest to, że sztucznie stawia jedzenie wyżej niż rozmnażanie co [nie zawsze ma miejsce w naturze](https://pl.wikipedia.org/wiki/Pawica_atlas) i może udałoby się to u nas. Może ktoś ma inny algorytm?

**Comment by xAdiro** [comment]
Rezygnujemy z priorytetów i stosujemy prosty algorytm opisany w #9. Podejście priorytetów jest ciekawe i generuje dużo parametrów przy których można grzebać, ale wydaje się niepotrzebnie skomplikowane, przynajmniej na początku.
