### ISSUE TITLE
Prototyp UI

### ISSUE THREAD

**Issue by Michal-Roman0** [Michal-Roman0/ProjektEwolucja#2]
Proste UI, tak żeby przynajmniej działało

**Comment by MariuszAKS** [comment]
Jak na razie jest możliwość zatrzymania i ruszenia symulacji, wybór różnych prędkości (od x1 do x32), oraz podgląd wybranego organizmu.

Zmiana prędkości symulacji bazuje na zmianie parametru Time.timeScale, który wpływa na Time.deltaTime. Tak więc zmiana prędkości będzie wpływała na każde obliczenie zawierające w sobie: x * Time.deltaTime, ale nie wpływa na częstość odpalania funkcji Update() w obiektach.

Panel zawierający opcje związane z czasem znajduje się w prawym górnym rogu.

Po naciśnięciu na przygotowane obiekty testowe, po prawej zostają wyświetlone ich parametry.

Jako że fragmenty mapy będą zawierać różne parametry takie jak: temperatura, gęstość roślinności, ciężkość poruszania się, to myślę że dobrym rozwiązaniem byłoby zrobienie kilku widoków mapy, między którymi można by się przełączać: mapa terenu, temperaturowa, zagęszczenia roślinności, etc., dzięki czemu można by się skupić na konkretnych parametrach przy podglądzie lub edycji środowiska.
Po wyborze konkretnego widoku, wyświetlone zostaną narzędzia edycji związane z określonym parametrem, dzięki czemu unikniemy zawalenia panelu edycji mnóstwem suwaków dotyczących różnych parametrów.
