### ISSUE TITLE
System Maszyny Stanowej do AI

### ISSUE THREAD

**Issue by Michal-Roman0** [Michal-Roman0/ProjektEwolucja#22]

**Comment by xAdiro** [comment]
![obraz](https://user-images.githubusercontent.com/51029232/229571836-e8ed5ced-ddbc-405e-8d0b-71c740afa40e.png)

**Comment by xAdiro** [comment]
Przejścia z going to food/mate do wandering powinny być sprawdzane tylko co jakiś czas, który jest cechą np. (nie)cierpliwość, albo określoną wartością. Może to być wartość stała albo rosnąć jeśli zmiany następują zbyt często (co też może być jakąś określoną funkcją, ale można ją też parametryzować cechą/ami)

**Comment by xAdiro** [comment]
Rezygnujemy z priorytetów, ustalamy proste algorytmiczne podejście na podstawie tego czy organizm jest głodny czy nie.
![image](https://user-images.githubusercontent.com/51029232/230225800-25fc2222-d497-4df4-aa06-4d60f2759421.png)
- Szczegóły nt. głodu w  #9
