### ISSUE TITLE
Ustalenie wpływu statystyk bazowych na pochodne

### ISSUE THREAD

**Issue by me-ve** [Michal-Roman0/ProjektEwolucja#25]

**Comment by xAdiro** [comment]
Moim pomysłem jest zeby każda statystyka pochodna była liniowo uzależniona od odpowiednich statystyk bazowych czyli np:

Max speed = a<sub>0</sub>⋅Agility - a<sub>1</sub>⋅Size

Warte uwagi:
- mamy sobie jakieś określone współczynniki a<sub>n</sub>, które mówią jak duży wpływ ma dana cecha bazowa na pochodną. Będą jakieś domyślne wartości które użytkownik może zmieniać
- żeby łatwo określać która cecha wpływa negatywnie/pozytywnie na cechę pochodną wszystkie wspołczynniki są nieujemne, a w równaniu wstawiamy odpowiednio + albo - (tutaj + przy Agility, - przy Size)

**Comment by xAdiro** [comment]
- #23 to w sumie część tego issue

**Comment by xAdiro** [comment]
### Na podstawie worda

#### Cechy Bazowe:
- Agility
- Strength
- Stealth
- Sight (distance, angle)
- Sense (radius, efficiency)
- Size
- Morality

#### Cechy pochodne:
- Stamina
- Health
- Max speed
- Max energy
- Damage
- Threat (to z #23)

**Comment by xAdiro** [comment]
Moje sugestie:
- Stamina (-Size, +Agility)
- Health(+Size, +Strength)
- Max speed(-Size, +Agility)
- Max energy(+Size, -wszystkie)
- Damage(+Strength)
- Threat(+Size, +Strength)
