### ISSUE TITLE
PrzetestowanieHashsetów

### ISSUE THREAD

**Issue by Michal-Roman0** [Michal-Roman0/ProjektEwolucja#37]
Hashsety w pliku StateController.cs automatycznie są zarządzane przez funkcje onTriggerEnter2D i onTriggerExit2D. Sprawdzić, czy gdy jednostka zostanie usunięta funkcją Destroy() w zasięgu widzenia, to funkcja onTriggerExis2D poprawnie usunie tę jednostkę z hashsetu

**Comment by xAdiro** [comment]
Sprawdzone działa poprawnie
