### ISSUE TITLE
AI drapieżników

### ISSUE THREAD

**Issue by Michal-Roman0** [Michal-Roman0/ProjektEwolucja#8]
Zrobić opis, co jest potrzebne w tym AI

**Comment by xAdiro** [comment]
Trzeba jakoś mądrze rozwiązać kwestie walki pomiędzy mięsożercami. Myślę że zbliżeni genetycznie nie powinni się atakować, chociaż może to istnieć jako oddzielna cecha "kanibalizm"

**Comment by xAdiro** [comment]
Bardzo dużo jest podobne co w #9. Dokładne zmiany to

#### Rozmnażanie
bez zmian

#### Jedzenie
- jedzeniem są inne organizmy, wszyscy roślinożercy i niektórzy mięsożercy
- na podstawie #23 określane jest czy inny mięsożerca nadaje się do ataku. W przypadku gdy dwóch mięsożerców walczy ze sobą oboje tracą energie i hp i jeden zjada drugiego. Kiedy jeden mięsożerca jest groźniejszy od drugiego, ten pierwszy próbuje zaatakować drugiego, a drugi próbuje uciec.

#### Ucieczka
- jak wspomniane w razie różnego stopnia groźności, ucieka ten mniej groźny od bardziej groźnego.

![image](https://user-images.githubusercontent.com/51029232/230235726-2d543b71-02a3-4c7a-8051-30cc88bf7c1c.png)
