### ISSUE TITLE
AI roślinożerców

### ISSUE THREAD

**Issue by Michal-Roman0** [Michal-Roman0/ProjektEwolucja#9]
Zrobić opis, co jest potrzebne w tym AI

**Comment by xAdiro** [comment]
Temat jest częścią #22.
Akcje roślinożercy można podzielić na 3 rodzaje:
- związane z jedzeniem
- związane z rozmnażaniem
- ucieczka

#### Jedzenie
- jedzą rośliny generowane na mapie
- jeśli organizm jest głodny to idzie szukać jedzenia
- organizm robi się głodny kiedy wartość energii spadnie poniżej określonego progu x*Energia potrzebna do kopulacji, gdzie x można dostosować ręcznie albo dać jako cechę (x oczywiście > 1)
- organizm przestaje być głodny jeżeli jego energia przekroczy określony próg x%*max energia. Ogólnie chodzi o wyeliminowanie scenariusza gdzie przykładowo roślina daje 10% energii (akurat tego organizmu) i ten najedzony na 99% będzie dalej szukał bez sensu jedzenia.
![image](https://user-images.githubusercontent.com/51029232/230220327-695e14f1-b601-4a7c-9a81-204d139336d8.png)

#### Rozmnażanie
- jeśli organizm jest najedzony i nie ma cooldownu na rozmnażanie, zacznie poszukiwać partnera
- jeśli zobaczy potencjalnego partnera to idzie w jego stronę
- jeśli dwaj potencjalni partnerzy się spotkają pobierana jest od nich jakaś energia, oboje dostają cooldown na rozmnażanie i pojawia się nowy organizm 

Potencjalny partner musi spełniać warunki:
- być najedzony
- być wystarczająco podobny genetycznie #4 (zrezygnowałbym koncept prawdopodobieństw i został przy ustalonej granicy wymaganego podobieństwa, które można też w UI zmieniać)
- nie ma rozmnażania na cooldownie
![image](https://user-images.githubusercontent.com/51029232/230233950-1a19e477-9e52-42fa-95d1-6b1271ce92de.png)



#### Ucieczka
- jeśli widzi drapieżnika albo kilku, ucieka. Żeby znać kierunek liczymy kąty pomiędzy wektorami odległości drapieżników i idziemy tam gdzie ten kąt jest największy.
![image](https://user-images.githubusercontent.com/51029232/230224885-3bb0bef6-d250-4a63-ba45-e4f60e909438.png)

### Podsumowanie
"No fed mate around" i "No food around" są scenariuszami kiedy w jakiś okolicznościach wybrany wcześniej cel przestał być odpowiedni.
![image](https://user-images.githubusercontent.com/51029232/230225126-67bb1cb5-ad1f-4c41-b6dd-d4c8eea44ae4.png)
